import { analyticsService } from '@/features/analytics/api/analytics.api';
import { authService } from '@/features/auth/api/auth.api';
import { branchService } from '@/features/branches/api/branch.api';
import { menuService } from '@/features/menu/api/menu.api';
import { userService } from '@/features/users/api/user.api';
import { venueService } from '@/features/venue/api/venue.api';

export { ApiError, apiClient, toQueryString } from './axios';
export type {
  ApiEnvelope,
  AnalyticsSummary,
  Branch,
  BranchManagement,
  BranchManagementResponse,
  BranchOption,
  BranchOptionsResponse,
  BranchOverviewResponse,
  BranchQrResponse,
  BranchStats,
  BranchListResponse,
  CreateBranchInput,
  CreateCategoryInput,
  CreateItemInput,
  CreateMenuInput,
  CreateVenueUserInput,
  CurrentUser,
  ApproveExtractionResponse,
  ExtractedCategory,
  ExtractedItem,
  ExtractedMenu,
  ExtractedPrice,
  ExtractionJob,
  ExtractionJobResponse,
  ExtractionJobStatus,
  ExtractionLimits,
  ListQueryOptions,
  LocalizedText,
  LocalizedValue,
  OpeningHours,
  Menu,
  MenuAnalytics,
  MenuCategory,
  MenuItem,
  MenuItemPrice,
  MenuQrCode,
  PaginationMeta,
  PublicAnalyticsEventInput,
  PublicAnalyticsEventType,
  PublicBranch,
  PublicBranchMenuResponse,
  PublicVenue,
  PublicVenueListResponse,
  PublicVenueResponse,
  SetupVenueInput,
  StartExtractionResponse,
  UpdateBranchInput,
  UpdateCategoryInput,
  UpdateItemInput,
  UpdateMeInput,
  UpdateUserBranchesInput,
  UpdatePasswordInput,
  UpdateVenueInput,
  UserListResponse,
  UpdateMenuInput,
  Venue,
  VenueUser,
} from './types';

export const api = {
  register: authService.register,
  login: authService.login,
  verifyOtp: authService.verifyOtp,
  logout: authService.logout,
  me: authService.me,
  updateMe: authService.updateMe,
  updatePassword: authService.updatePassword,
  analyticsSummary: analyticsService.summary,
  myVenue: venueService.myVenue,
  setupVenue: venueService.setupVenue,
  updateVenue: venueService.updateVenue,
  users: userService.users,
  createUser: userService.createUser,
  updateUserBranches: userService.updateUserBranches,
  deleteUser: userService.deleteUser,
  branches: branchService.branches,
  branchOptions: branchService.branchOptions,
  branchManagement: branchService.branchManagement,
  branchOverview: branchService.branchOverview,
  branchQr: branchService.branchQr,
  regenerateBranchQr: branchService.regenerateBranchQr,
  branch: branchService.branch,
  createBranch: branchService.createBranch,
  updateBranch: branchService.updateBranch,
  setMainBranch: branchService.setMainBranch,
  deleteBranch: branchService.deleteBranch,
  branchMenu: menuService.branchMenu,
  createBranchMenu: menuService.createBranchMenu,
  updateBranchMenu: menuService.updateBranchMenu,
  publishBranchMenu: menuService.publishBranchMenu,
  unpublishBranchMenu: menuService.unpublishBranchMenu,
  createCategory: menuService.createCategory,
  updateCategory: menuService.updateCategory,
  deleteCategory: menuService.deleteCategory,
  reorderCategories: menuService.reorderCategories,
  createItem: menuService.createItem,
  updateItem: menuService.updateItem,
  deleteItem: menuService.deleteItem,
  reorderItems: menuService.reorderItems,
  toggleItemAvailability: menuService.toggleItemAvailability,
  latestExtractionJob: menuService.latestExtractionJob,
  extractionJob: menuService.extractionJob,
  startExtraction: menuService.startExtraction,
  retryExtraction: menuService.retryExtraction,
  approveExtraction: menuService.approveExtraction,
  rejectExtraction: menuService.rejectExtraction,
};
