import { analyticsService } from '@/features/menu/analytics/api/analytics.api';
import { authService } from '@/features/auth/api/auth.api';
import { branchService } from '@/features/branches/api/branch.api';
import { feedbackService } from '@/features/feedback/api/feedback.api';
import { financialService } from '@/features/financial/api/financial.api';
import { menuService } from '@/features/menu/api/menu.api';
import { subscriptionService } from '@/features/subscription/api/subscription.api';
import { userService } from '@/features/users/api/user.api';
import { venueService } from '@/features/venue/api/venue.api';

export { ApiError, apiClient, toQueryString } from './axios';
export type {
  ApiEnvelope,
  AdminVerificationCodesResponse,
  AdminVerificationCodeStatus,
  AdminVerificationUser,
  AdminFeaturesResponse,
  AdminPlansResponse,
  AdminSubscriptionOverview,
  AdminVenuesResponse,
  AnalyticsSummary,
  Branch,
  BranchManagement,
  BranchManagementResponse,
  BranchOption,
  BranchOptionsResponse,
  BranchOverviewResponse,
  BranchQrResponse,
  BranchStats,
  BranchListResponse,
  CreateBranchInput,
  CreateCategoryInput,
  CreateItemInput,
  CreateMenuInput,
  CreatePlanFeatureMappingInput,
  CreateVenueUserInput,
  CurrentUser,
  ApproveExtractionResponse,
  ExtractedCategory,
  ExtractedItem,
  ExtractedMenu,
  ExtractedPrice,
  ExtractionJob,
  ExtractionJobResponse,
  ExtractionJobStatus,
  ExtractionLimits,
  FeedbackDashboardResponse,
  GuestFeedback,
  GuestFeedbackStatus,
  ImageUploadScope,
  ImageUploadSignature,
  ListQueryOptions,
  LocalizedText,
  LocalizedValue,
  OpeningHours,
  Menu,
  MenuPlanCode,
  MenuAnalytics,
  MenuCategory,
  MenuItem,
  MenuItemPrice,
  MenuQrCode,
  PaginationMeta,
  PublicAnalyticsEventInput,
  PublicAnalyticsEventType,
  PublicBranch,
  PublicBranchMenuResponse,
  PublicFeedbackInput,
  PublicFeedbackResponse,
  PublicVenue,
  PublicVenueListResponse,
  PublicVenueResponse,
  SetupVenueInput,
  StartExtractionResponse,
  SubscriptionStatus,
  TenantSubscriptionResponse,
  UpdateBranchInput,
  UpdateCategoryInput,
  UpdateItemInput,
  UpdateMeInput,
  UpdateUserBranchesInput,
  UpdatePasswordInput,
  UpdateVenueSubscriptionInput,
  UpdateVenueInput,
  UserListResponse,
  UpdateMenuInput,
  UpdatePlanFeatureInput,
  UpdatePlanFeatureMappingInput,
  UpdatePlanInput,
  Venue,
  VenueUser,
} from './types';

export const api = {
  register: authService.register,
  login: authService.login,
  verifyOtp: authService.verifyOtp,
  adminVerificationCodes: authService.adminVerificationCodes,
  regenerateAdminVerificationCode: authService.regenerateAdminVerificationCode,
  logout: authService.logout,
  me: authService.me,
  updateMe: authService.updateMe,
  updatePassword: authService.updatePassword,
  analyticsSummary: analyticsService.summary,
  feedbackDashboard: feedbackService.dashboard,
  updateFeedbackStatus: feedbackService.updateStatus,
  financeAccess: financialService.access,
  financeDashboard: financialService.dashboard,
  financialTransactions: financialService.transactions,
  createFinancialTransaction: financialService.createTransaction,
  updateFinancialTransaction: financialService.updateTransaction,
  deleteFinancialTransaction: financialService.deleteTransaction,
  transactionCategories: financialService.categories,
  createTransactionCategory: financialService.createCategory,
  updateTransactionCategory: financialService.updateCategory,
  deleteTransactionCategory: financialService.deleteCategory,
  paymentMethods: financialService.paymentMethods,
  createPaymentMethod: financialService.createPaymentMethod,
  updatePaymentMethod: financialService.updatePaymentMethod,
  deletePaymentMethod: financialService.deletePaymentMethod,
  financialAnalytics: financialService.analytics,
  financialReport: financialService.report,
  subscription: subscriptionService.tenant,
  adminSubscriptionOverview: subscriptionService.adminOverview,
  adminSubscriptionVenues: subscriptionService.adminVenues,
  updateVenueSubscription: subscriptionService.updateVenueSubscription,
  adminPlans: subscriptionService.adminPlans,
  adminFeatures: subscriptionService.adminFeatures,
  updatePlan: subscriptionService.updatePlan,
  updatePlanFeature: subscriptionService.updateFeature,
  createPlanFeatureMapping: subscriptionService.createMapping,
  updatePlanFeatureMapping: subscriptionService.updateMapping,
  myVenue: venueService.myVenue,
  setupVenue: venueService.setupVenue,
  updateVenue: venueService.updateVenue,
  users: userService.users,
  createUser: userService.createUser,
  updateUserBranches: userService.updateUserBranches,
  deleteUser: userService.deleteUser,
  branches: branchService.branches,
  branchOptions: branchService.branchOptions,
  branchManagement: branchService.branchManagement,
  branchOverview: branchService.branchOverview,
  branchQr: branchService.branchQr,
  regenerateBranchQr: branchService.regenerateBranchQr,
  branch: branchService.branch,
  createBranch: branchService.createBranch,
  updateBranch: branchService.updateBranch,
  setMainBranch: branchService.setMainBranch,
  deleteBranch: branchService.deleteBranch,
  branchMenu: menuService.branchMenu,
  createBranchMenu: menuService.createBranchMenu,
  updateBranchMenu: menuService.updateBranchMenu,
  publishBranchMenu: menuService.publishBranchMenu,
  unpublishBranchMenu: menuService.unpublishBranchMenu,
  createCategory: menuService.createCategory,
  updateCategory: menuService.updateCategory,
  deleteCategory: menuService.deleteCategory,
  reorderCategories: menuService.reorderCategories,
  createItem: menuService.createItem,
  updateItem: menuService.updateItem,
  deleteItem: menuService.deleteItem,
  reorderItems: menuService.reorderItems,
  toggleItemAvailability: menuService.toggleItemAvailability,
  latestExtractionJob: menuService.latestExtractionJob,
  extractionJob: menuService.extractionJob,
  startExtraction: menuService.startExtraction,
  retryExtraction: menuService.retryExtraction,
  approveExtraction: menuService.approveExtraction,
  rejectExtraction: menuService.rejectExtraction,
};
