import { authService } from './services/auth.service';
import { analyticsService } from './services/analytics.service';
import { branchService } from './services/branch.service';
import { menuService } from './services/menu.service';
import { userService } from './services/user.service';
import { venueService } from './services/venue.service';

export { ApiError, apiClient, toQueryString } from './client';
export type {
  ApiEnvelope,
  AnalyticsSummary,
  Branch,
  BranchManagement,
  BranchManagementResponse,
  BranchOption,
  BranchOptionsResponse,
  BranchOverviewResponse,
  BranchQrResponse,
  BranchStats,
  BranchListResponse,
  CreateBranchInput,
  CreateCategoryInput,
  CreateItemInput,
  CreateMenuInput,
  CreateVenueUserInput,
  CurrentUser,
  ListQueryOptions,
  LocalizedText,
  LocalizedValue,
  OpeningHours,
  Menu,
  MenuAnalytics,
  MenuCategory,
  MenuItem,
  MenuItemPrice,
  MenuQrCode,
  PaginationMeta,
  SetupVenueInput,
  UpdateBranchInput,
  UpdateCategoryInput,
  UpdateItemInput,
  UpdateMeInput,
  UpdateUserBranchesInput,
  UpdatePasswordInput,
  UserListResponse,
  UpdateMenuInput,
  Venue,
  VenueUser,
} from './types';

export const api = {
  register: authService.register,
  login: authService.login,
  verifyOtp: authService.verifyOtp,
  logout: authService.logout,
  me: authService.me,
  updateMe: authService.updateMe,
  updatePassword: authService.updatePassword,
  analyticsSummary: analyticsService.summary,
  myVenue: venueService.myVenue,
  setupVenue: venueService.setupVenue,
  users: userService.users,
  createUser: userService.createUser,
  updateUserBranches: userService.updateUserBranches,
  branches: branchService.branches,
  branchOptions: branchService.branchOptions,
  branchManagement: branchService.branchManagement,
  branchOverview: branchService.branchOverview,
  branchQr: branchService.branchQr,
  branch: branchService.branch,
  createBranch: branchService.createBranch,
  updateBranch: branchService.updateBranch,
  setMainBranch: branchService.setMainBranch,
  deleteBranch: branchService.deleteBranch,
  branchMenu: menuService.branchMenu,
  createBranchMenu: menuService.createBranchMenu,
  updateBranchMenu: menuService.updateBranchMenu,
  publishBranchMenu: menuService.publishBranchMenu,
  unpublishBranchMenu: menuService.unpublishBranchMenu,
  createCategory: menuService.createCategory,
  updateCategory: menuService.updateCategory,
  deleteCategory: menuService.deleteCategory,
  reorderCategories: menuService.reorderCategories,
  createItem: menuService.createItem,
  updateItem: menuService.updateItem,
  deleteItem: menuService.deleteItem,
  reorderItems: menuService.reorderItems,
  toggleItemAvailability: menuService.toggleItemAvailability,
};
